import Constants from 'expo-constants';
import * as Application from 'expo-application';
import { Platform } from 'react-native';

const config = Constants.expoConfig || Constants.manifest || {};
const ios = config.ios || {};
const android = config.android || {};
const extra = config.extra || {};
const appName = config.name || '';
const version = config.version || Application.nativeApplicationVersion || '';
const build = Platform.OS === 'ios'
  ? (ios.buildNumber || Application.nativeBuildVersion || '')
  : (android.versionCode || Application.nativeBuildVersion || '');
const apiUrl = String(extra.productionApiUrl || process.env.EXPO_PUBLIC_API_URL || process.env.EXPO_PUBLIC_SUPABASE_URL || '');
const isProductionApi = apiUrl.startsWith('https://') && !/localhost|127\.0\.0\.1|staging|dev\b/i.test(apiUrl);

const item = (id, title, description, platform, status, severity, fixSuggestion, detectedValue = 'Илрүүлээгүй', expectedValue = 'Шаардлагад нийцсэн') => ({ id, title, description, platform, status, severity, fixSuggestion, detectedValue, expectedValue });
const manual = (id, title, description, platform, fix = 'Store Console дээр гараар шалгаж, утгыг баталгаажуулна уу.') => item(id, title, description, platform, 'manual', 'info', fix, 'Гараар шалгах шаардлагатай', 'Баталгаажсан store мэдээлэл');

export function runStoreReadinessChecks() {
  const common = [
    item('https', 'HTTPS ашиглаж байгаа эсэх', 'Сүлжээний production endpoint HTTPS эсэхийг шалгана.', 'both', isProductionApi ? 'passed' : 'failed', 'high', 'Production API URL-ийг HTTPS хаягаар тохируулна уу.', apiUrl || 'API URL алга', 'https://...'),
    item('production-api', 'Production API endpoint', 'Local, dev эсвэл staging endpoint ашиглаагүй эсэх.', 'both', isProductionApi ? 'passed' : 'failed', 'high', 'EXPO_PUBLIC_API_URL-ийг production endpoint-оор солино уу.', apiUrl || 'API URL алга', 'Production HTTPS endpoint'),
    manual('crash-review', 'Crash болон runtime error', 'Сүүлийн release build дээр obvious crash, unhandled error байхгүй эсэхийг шалгана.', 'both', 'Release build-ийг төхөөрөмж дээр тестлээд crash log шалгана уу.'),
    manual('placeholder-content', 'Placeholder/demo content', 'Түр текст, demo өгөгдөл үлдсэн эсэхийг шалгана.', 'both'),
  ];
  const apple = [
    item('ios-app-name', 'App name байгаа эсэх', 'Expo app name тохирсон эсэх.', 'apple', appName ? 'passed' : 'failed', 'high', 'app.json/app.config.js дотор expo.name тохируулна уу.', appName || 'Алга', 'Нэртэй'),
    item('ios-bundle-id', 'Bundle Identifier зөв эсэх', 'iOS bundle identifier тохирсон эсэх.', 'apple', ios.bundleIdentifier ? 'passed' : 'failed', 'high', 'ios.bundleIdentifier тохируулна уу.', ios.bundleIdentifier || 'Алга', 'com.company.app'),
    item('ios-version-build', 'Version болон Build number', 'Version болон build дугаарын config байгаа эсэх.', 'apple', version && build ? 'passed' : 'failed', 'high', `${version ? '' : 'Version '} ${build ? '' : 'Build number '}тохируулна уу.`, `${version || '—'} / ${build || '—'}`, 'Version + build'),
    item('ios-icon', 'App icon шаардлагатай хэмжээнүүд', 'Icon asset заасан эсэхийг шалгана; бүх хэмжээг Apple-ийн build tool баталгаажуулна.', 'apple', config.icon ? 'warning' : 'failed', 'high', '1024px App Store icon болон native icon-уудыг шалгана уу.', config.icon || 'Алга', 'icon asset'),
    item('ios-launch', 'Launch screen байгаа эсэх', 'Splash/launch screen config байгаа эсэх.', 'apple', config.splash ? 'passed' : 'failed', 'medium', 'expo.splash болон native launch screen тохируулна уу.', config.splash ? 'Тохируулсан' : 'Алга', 'Launch screen'),
    manual('ios-privacy-url', 'Privacy Policy URL', 'App Store Connect-ийн Privacy Policy URL.', 'apple'), manual('ios-support-url', 'Support URL', 'App Store Connect-ийн Support URL.', 'apple'), manual('ios-description', 'App description', 'Store listing description.', 'apple'), manual('ios-keywords', 'Keywords', 'Store listing keywords.', 'apple'), manual('ios-category', 'Category', 'App Store category.', 'apple'), manual('ios-age-rating', 'Age Rating', 'Age rating questionnaire.', 'apple'), manual('ios-app-privacy', 'App Privacy мэдээлэл', 'Collected data declarations.', 'apple'),
    item('ios-camera-purpose', 'Camera permission purpose text', 'Camera ашигладаг тул native purpose text байгаа эсэх.', 'apple', ios.infoPlist?.NSCameraUsageDescription ? 'passed' : 'failed', 'high', 'NSCameraUsageDescription тохируулна уу.', ios.infoPlist?.NSCameraUsageDescription || 'Алга', 'Тодорхой purpose text'),
    item('ios-location-purpose', 'Location permission purpose text', 'Location ашигладаг тул purpose text байгаа эсэх.', 'apple', ios.infoPlist?.NSLocationWhenInUseUsageDescription ? 'passed' : 'failed', 'high', 'NSLocationWhenInUseUsageDescription тохируулна уу.', ios.infoPlist?.NSLocationWhenInUseUsageDescription || 'Алга', 'Тодорхой purpose text'),
    item('ios-microphone-purpose', 'Microphone permission purpose text', 'Microphone ашигладаг тул purpose text байгаа эсэх.', 'apple', ios.infoPlist?.NSMicrophoneUsageDescription ? 'passed' : 'failed', 'high', 'NSMicrophoneUsageDescription тохируулна уу.', ios.infoPlist?.NSMicrophoneUsageDescription || 'Алга', 'Тодорхой purpose text'),
    item('ios-photos-purpose', 'Photo Library purpose text', 'Photo Library ашигладаг тул purpose text байгаа эсэх.', 'apple', ios.infoPlist?.NSPhotoLibraryUsageDescription ? 'passed' : 'failed', 'high', 'NSPhotoLibraryUsageDescription тохируулна уу.', ios.infoPlist?.NSPhotoLibraryUsageDescription || 'Алга', 'Тодорхой purpose text'),
    manual('ios-account-delete', 'Account deletion', 'Sign in ашигладаг бол account устгах боломж.', 'apple'), manual('ios-apple-signin', 'Sign in with Apple', 'Google/Facebook login ашигладаг эсэх ба шаардлагатай бол Apple login.', 'apple'), manual('ios-iap', 'In-app purchase', 'IAP ашигладаг эсэх болон product тохиргоо.', 'apple'), manual('ios-att', 'Tracking ба ATT', 'Tracking ашигладаг бол AppTrackingTransparency тохиргоо.', 'apple'),
    item('ios-debug', 'Debug mode унтарсан эсэх', 'Release build debug биш байх ёстой.', 'apple', 'manual', 'high', 'Release configuration-аар archive хийж, debug flag шалгана уу.', 'Гараар шалгах шаардлагатай', 'Debug=false'), manual('ios-config', 'Crash үүсгэх config', 'Production config болон native entitlement-үүдийг шалгана.', 'apple'), manual('ios-demo', 'Test/demo credential', 'Store review-д зориулсан credential зөв эсэх.', 'apple'), manual('ios-screenshots', 'Screenshot-ууд', 'Бүх шаардлагатай device screenshot бэлэн эсэх.', 'apple'), manual('ios-metadata', 'App Store metadata', 'Metadata бүрэн эсэх.', 'apple'),
  ];
  const google = [
    item('android-app-id', 'Application ID зөв эсэх', 'Android package/applicationId тохирсон эсэх.', 'google', android.package ? 'passed' : 'failed', 'high', 'android.package тохируулна уу.', android.package || 'Алга', 'com.company.app'),
    item('android-version-code', 'Version Code', 'Android versionCode байгаа эсэх.', 'google', android.versionCode ? 'passed' : 'failed', 'high', 'android.versionCode нэмнэ үү.', String(android.versionCode || 'Алга'), 'Эерэг бүхэл тоо'),
    item('android-version-name', 'Version Name', 'Android versionName/version байгаа эсэх.', 'google', version ? 'passed' : 'failed', 'high', 'expo.version тохируулна уу.', version || 'Алга', '1.0.0'), manual('android-aab', 'Android App Bundle (.aab)', 'Release AAB build хийх боломжийг EAS/Gradle build-ээр шалгана.', 'google'), manual('android-target-sdk', 'Target SDK', 'Google Play-ийн одоогийн target SDK шаардлага.', 'google'), manual('android-min-sdk', 'Min SDK', 'Төхөөрөмжийн дэмжлэг ба min SDK.', 'google'),
    item('android-icon', 'App icon', 'Expo icon asset байгаа эсэх.', 'google', config.icon ? 'passed' : 'failed', 'high', 'expo.icon тохируулна уу.', config.icon || 'Алга', 'icon asset'), manual('android-adaptive-icon', 'Adaptive icon', 'Android adaptive icon foreground/background.', 'google'), manual('android-privacy-url', 'Privacy Policy URL', 'Play Console privacy policy.', 'google'), manual('android-data-safety', 'Data Safety мэдээлэл', 'Data Safety form-д шаардлагатай өгөгдөл.', 'google'), manual('android-content-rating', 'Content Rating', 'Play Console content rating.', 'google'), manual('android-audience', 'Target Audience', 'Зорилтот насны бүлэг.', 'google'), manual('android-ads', 'Ads ашигладаг эсэх', 'Ads declaration.', 'google'),
    manual('android-location', 'Location permission', 'Location зөвшөөрөл шаардлагатай эсэх.', 'google'), manual('android-background-location', 'Background location', 'Background location ашигладаг эсэх, declaration.', 'google'), manual('android-camera', 'Camera permission', 'Camera зөвшөөрөл шаардлагатай эсэх.', 'google'), manual('android-microphone', 'Microphone permission', 'Microphone зөвшөөрөл шаардлагатай эсэх.', 'google'), manual('android-storage', 'Storage/media permission', 'Media/storage permission зөв эсэх.', 'google'), manual('android-notification', 'Notification permission', 'POST_NOTIFICATIONS болон тайлбар.', 'google'), manual('android-foreground-service', 'Foreground service', 'Foreground service declaration.', 'google'), manual('android-sensitive', 'Sensitive permission', 'Sensitive permission policy compliance.', 'google'), manual('android-account-delete', 'Account deletion', 'Account үүсгэдэг бол устгах зам.', 'google'), manual('android-login', 'Login test account', 'Review-д зориулсан тест account.', 'google'),
    item('android-debuggable', 'Debuggable=false', 'Release manifest debug биш эсэхийг config-аас бүрэн батлах боломжгүй.', 'google', 'manual', 'high', 'Release AAB manifest-ийг шалгаад debuggable=false болгоно уу.', 'Гараар шалгах шаардлагатай', 'false'), manual('android-signing', 'Keystore/release signing', 'Release signing тохирсон эсэх.', 'google'), manual('android-placeholder', 'Placeholder/demo content', 'Demo болон түр агуулга үлдээгүй эсэх.', 'google'), manual('android-description', 'Store listing description', 'Play Store description.', 'google'), manual('android-screenshots', 'Screenshots', 'Play Store screenshots.', 'google'), manual('android-feature-graphic', 'Feature Graphic', 'Play Store feature graphic.', 'google'),
  ];
  return { generatedAt: new Date().toISOString(), checks: [...common, ...apple, ...google], config: { name: appName, version, build, iosBundleId: ios.bundleIdentifier || null, androidPackage: android.package || null, apiUrl: apiUrl || null } };
}

export const STATUS_LABELS = { passed: 'Бэлэн', warning: 'Анхаарах', failed: 'Дутуу', manual: 'Гараар шалгах шаардлагатай' };
